const CarouselData = [
    {
      id: 1,
      src: "https://ik.imagekit.io/m1akscp5q/11.png?updatedAt=1702111096135",
      href: "#link1",
      alt: "Nature Image 1",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 2,
      src: "https://ik.imagekit.io/m1akscp5q/foto3.png?updatedAt=1702110929667",
      href: "#link2",
      alt: "Nature Image 2",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 3,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link3",
      alt: "Nature Image 3",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 4,
      src: "https://ik.imagekit.io/m1akscp5q/aiony-haust-3TLl_97HNJo-unsplash%202.png?updatedAt=1702110574421",
      href: "#link4",
      alt: "Nature Image 4",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 5,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 6,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 7,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 8,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 9,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 10,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    {
      id: 11,
      src: "https://ik.imagekit.io/m1akscp5q/Mask%20group2.png?updatedAt=1702110929654",
      href: "#link5",
      alt: "Ketut Camprut S.Pd, M.Pd",
      title: "Ketut Camprut S.Pd, M.Pd",
      partai: "Partai Nasdem",
      logoPartai:"https://ik.imagekit.io/m1akscp5q/Partai_NasDem%201.png?updatedAt=1702182972768",
      name:"Ketut Camprut S.Pd, M.Pd",
      dapil:"Dapil Sumatera Utara",
    },
    // ... other objects
  ];
  
  export default CarouselData;

  